### ISSUE TITLE
Desktop browser related issue

### ISSUE THREAD

**Issue by Datamato7** [bitbar/bitbar-samples#193]
Hi,

For running desktop based application on bitbar for windows what should be the contents of run-tests.ps1? And how to run it?

**Comment by Datamato7** [comment]
Creating a Run
"Creating the test package. The Selenium test suite needs to be packaged into a zip file that has at its root a run-tests.sh (for Linux and Mac based browser test runs) or a PowerShell run-tests.ps1 file for Windows based test runs."  But What will be the contents of run-tests.ps1 file.

**Comment by Datamato7** [comment]
Sample tests are in python. Is it available for Java?

**Comment by aknackiron** [comment]
Hello, to get started I suggest you have a look at what's inside of run-tests.sh shell scripts. We'll come with ps1 samples later on. The ps1 script should call your test execution framework. For a Java test you'll probably call Maven or Java directly to get the test started.
Unfortunately for now, we don't have any Java sample.

I suggest you ping our sales at sales @ bitbar.com and some customer success engineer can help you out getting started!

**Comment by lastverb** [comment]
Selenium tests are being executed using client - server architecture. Mentioned `run-test.sh` script is starting client of Selenium test, which Bitbar does run on Unix-based machines. Server with browser that processes selenium driver calls can be on different machine of any os, which means that test (python using selenium webdriver in samples) started by run_test.sh can use browser on any os (including Windows).

Samples provided in this repository under samples/testing-frameworks/desktop-browsers/ will work with any targeted browser on cloud.bitbar.com (currently only Windows based). You can use client-side samples to use your local machine as client of selenium test using Bitbar hosted browsers, or server-side samples to use Bitbar machines as clients.

As for sever-side samples in Java - they will probably come. I don't know when. As long as test is targeting `http://localhost:4723/wd/hub` as selenium hub (server), `run-test.sh` would only need to start the jar (java -jar ...). I'm not sure maven build would work on Bitbar client machines (javac might, but you would need to download all dependencies manually).

I have found the source of that citation, it might need to be fixed.

**Comment by Datamato7** [comment]
Hi,

I was trying to execute my tests on bitbar with given run-tests.sh file
just by changing name of test in that file. that file has one line "python"
followed by test name so I changed the test name and run my test but its
failing. As my test is in java so with python command will my test run?
What kind of change should be needed in run-tests.sh file to run my java
based test on bitbar(server side). Please let me know.

Thanks,
Sneha
